apiVersion: cert-manager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: multik8s-thecosmicfrog-org-tls
spec:
  secretName: multik8s-thecosmicfrog-org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multik8s.thecosmicfrog.org
  dnsNames:
    - multik8s.thecosmicfrog.org
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - multik8s.thecosmicfrog.org

